### ISSUE TITLE
program MCU to read the value of that switch

### ISSUE THREAD

**Issue by fahrrad** [jenpaff/sven#2]

**Comment by jenpaff** [comment]
Implemented it the following way (see commit : https://github.com/jenpaff/sven/commit/59c67980da0509bd319571f8dccb8a314a874dd3) 

- if the switch is open, timer starts checking how long it's been open
- if open longer than a certain threshold (should be 30sec, atm for testing set to 5 sec) turn on led
- after that a warning will be send  in a specific interval (also 30sec, atm for testing set to 5 sec)
- when the door is closed, the values will be reset

NOTE: most of the logs can be removed after testing

@fahrrad please feel free to make changes in the code I committed to make it more efficient, more readable or whatever . otherwise I think we can close this one, just keeping it open for you to have a look if anything is missing
